# .github/workflows/etl_weekly.yml
name: ETL weekly
on: { schedule: [ { cron: "0 9 1 * *" } ], workflow_dispatch: {} } # At 09:00 on day-of-month 1.
jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Show repo and requirements
        run: |
          pwd; ls -la
          echo "---- requirements.txt ----"
          sed -n '1,120p' requirements.txt || true
          echo "---- end requirements.txt ----"
      - name: Install deps
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --no-cache-dir -r "$GITHUB_WORKSPACE/requirements.txt"
          python -m pip show google-cloud-bigquery
      - name: Auth
        env: 
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS" > /tmp/gcp.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp.json" >> $GITHUB_ENV
      - name: Run ETL
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BQ_PROJECT_ID: ${{ env.BQ_PROJECT_ID }}
          PG_DSN: ${{ secrets.PG_DSN }}
        run: python etl.py
