# .github/workflows/etl_weekly.yml
name: ETL weekly
on: { schedule: [ { cron: "0 9 * * MON" } ], workflow_dispatch: {} }
jobs:
  run-etl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.12" }
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Auth
        env: 
          GCP_SA_JSON: ${{ secrets.GCP_SA_JSON }}
        run: |
          echo "$GCP_SA_JSON" > /tmp/gcp.json
          export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp.json" >> $GITHUB_ENV
      - name: Run ETL
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          BQ_PROJECT_ID: ${{ secrets.BQ_PROJECT_ID }}
        run: python etl.py --resume
